name: Java CI with Maven
on:
 workflow_dispatch:
jobs:
  builds:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v6
    - name: Build Java package
      run: mvn clean install -f Javarepo1/pom.xml
    - name: Upload Artifact
      uses: actions/upload-artifact@v7
      with:
        name: my-artifact
        path: javarepo1/target/*.jar
